### PR TITLE
chore: fix intermediate parsing and clean up debug leg overview

### LINKED ISSUE #64: feat: parsing for intermediate stops
- implement another layer of parsing to ensure correctness for the comparison of intermediate stops

### PR DESCRIPTION
**Pull request by Kvnstrck**
closes #64 

#### Formalities:
- [x] PR targets `staging`, if compare branch is `chore/*` or `feat/*`
- [x] PR title is formatted as a [commit](https://www.conventionalcommits.org/en/v1.0.0/#specification)
- [x] New functions are commented in the source file
- [x] Notes are added to wiki

#### Quality assurance:
- Manual build and unit/component testing:
    - [x] Linux
    - [x] macOS
    - [ ] Windows
- Manual End-To-End testing:
    - [x] Upload of query batch
    - [x] Computation of routing results
    - [x] Download plan
    - [x] Upload plan
    - [x] Compare functionality
    - [x] Itinerary Overview 

#### For `staging -> master`
- [ ] Check for relevant open issues
- [ ] After merge: Create release

---

### CODE REVIEW

**Review by nicosvv — APPROVED** [review]

**Review by Kha1r0 — APPROVED** [review]

**Review by D3vZro — APPROVED** [review]

**Review by D3vZro — APPROVED** [review]

File: visual-debugger/src/lib/components/ui/ConnectionDetail.svelte [hunk 1]
```diff
@@ -179,7 +179,7 @@
                         </summary>
                         <div class="flex mb-1 grid gap-y-4 items-center">
                             {#each l.intermediateStops! as s}
-                                {@render stopTimes(s.arrival!, s.scheduledArrival!, l.realTime, s.name!, shadowItinerary.legs[i].endTime,s.stopId)} //TODO: change shadow to Intermediate stop arrival time boolean
+                                {@render stopTimes(s.arrival!, s.scheduledArrival!, l.realTime, s.name!, shadowItinerary.legs[i].intermediateStops,s.stopId)}
```
Comment (D3vZro) [inline visual-debugger/src/lib/components/ui/ConnectionDetail.svelte:182]: vdb-check fails there because of mismatched argument types. Weird thing is that the component implicitly demands type `boolean | undefined`, contrary to the class declaration in `comparisonShadows.ts`. Maybe because its optional?

Comment (Kvnstrck) [reply visual-debugger/src/lib/components/ui/ConnectionDetail.svelte:182]: This appears to be the exact case. Setting the parameter as non optional seems to fix the issue, fixed in 6fb9305

**Review by MoPhliFra — APPROVED** [review]
